# Generated by Django 4.2.1 on 2023-05-26 10:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_todo_updated_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='todo',
            managers=[
                ('yasin', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('', 'select work status'), ('P', 'Pending'), ('C', 'Completed')], max_length=255),
        ),
    ]
